### PR TITLE
Added support for bundlers

### LINKED ISSUE #1: No originalInstantiate
I'm using Webpack with the latest SystemJS and `System.constructor.prototype.instantiate` doesn't exist. This means that https://github.com/systemjs/systemjs-css-extra/blob/master/src/css.js#L39 throws an error.

### PR DESCRIPTION
**Pull request by stevenvachon**
Fixes #1

### CODE REVIEW

**Comment by stevenvachon** [comment]
@kouts?

**Comment by stevenvachon** [comment]
@guybedford?

**Comment by guybedford** [comment]
@stevenvachon Thanks for the PR and sorry I don't have much time for reviews at the moment - will take a look when I can.

Would you consider being a maintainer of this project?

**Comment by stevenvachon** [comment]
> Would you consider being a maintainer of this project?

Honestly, no, despite it possibly lowering the odds of this PR getting reviewed/merged, heh. I have enough open source projects already that I need to find time to improve/support.

**Comment by guybedford** [comment]
Just took another look at this. I'm pretty sure you can achieve the same in Webpack with the configuration:

```js
{
  module: {
    rules: [
      { parser: { system: false } }
    ]
  }
}
```

so I'm not sure we do need to merge this after all? Let me know.

> Honestly, no, despite it possibly lowering the odds of this PR getting reviewed/merged, heh.

Very sensible :) Transactional open source is a horrific thought.

**Comment by stevenvachon** [comment]
@guybedford I haven't tried that option, but I'd rather not rely on cross-project options, especially when I may be switching to Parcel v2 in the ~~near~~ future.

**Comment by stevenvachon** [comment]
Also, won't `system: false` disable `import(/* webpackChunkName: "name" */ 'path/to/file')`?

**Comment by kouts** [comment]
@stevenvachon ```import(/* webpackChunkName: "name" */ 'path/to/file')``` will work just fine, you only need to set ```parser: { system: false }``` into Webpack config as @guybedford suggested.

**Comment by stevenvachon** [comment]
I still think that, regardless of any webpack options, this is the correct way to target the global variable. It's also consistent with SystemJS core and its extras.

**Comment by stevenvachon** [comment]
@guybedford ^^

**Comment by stevenvachon** [comment]
I'm not sure if the silence means anything here.

**Comment by stevenvachon** [comment]
Well, anyway, I humoured you and tried the webpack config change, and it doesn't work. Please re-review this PR.

**Comment by guybedford** [comment]
@stevenvachon as you have gathered from the silence, it is not clear how well maintained this plugin will be. @kouts is the maintainer here not myself. Maintaining a fork for your own use cases may be the most sensible route forward.

**Comment by stevenvachon** [comment]
@guybedford I'd _really_ rather not do that. I like semver.
@kouts hello

**Comment by guybedford** [comment]
@stevenvachon that is not how open source works unfortunately. You work for a company and are paid to work on this. I have worked on SystemJS for 7 years and am lucky to pull in $300 per month for the project. You simply cannot **demand** service - the point of open source is that there is no service, there is no guarantee and you are on your own.

**Comment by stevenvachon** [comment]
@guybedford I don't even make $300 on my personal projects.

**Comment by guybedford** [comment]
@stevenvachon the point is your salary goes towards integrating this project, and you are demanding free labour to fix something for your company that is not deemed a problem here and we have provided an alternative solution. That support alone is worth gratitude not this tone, which will not get you far in open source at all unfortunately. I'm locking this issue from further discussion.

**Pull request closed without merging**
